### ISSUE TITLE
Localization with Gigabyte Map

### ISSUE THREAD

**Issue by David9696** [HViktorTsoi/FAST_LIO_LOCALIZATION#2]
Hi,

Thanks for your great package. 

I tried to test with my pcd map which is about 8gb size. Once it is loaded, the node would died. Is it because the map is too big?

If yes, how could I reduce the map size? The map is generated from fast lio package. Possible to use fast lio to generate map with smaller size?

Thanks.

David

**Comment by HViktorTsoi** [comment]
The map size in your scenario is indeed too large... in most of our tasks, the map size is < 0.5GB. When the map size is large, either the **pcl_ros** tool that publish the pcd file to ros message, or **RVIZ** may crash. Here are some possible solution

1. Downsample the pcd file saved from fastlio, you may easily use open3d to implement this with a few LOC, something like
```
import open3d
pcd = open3d.io.read_point_cloud('/path/to/your/large_map_fastlio.pcd')
open3d.io.write_point_cloud('/tmp/small_map_0.4meter_resolution.pcd', pcd.voxel_down_sample(0.4))
```
then use the downsampled pcd for localization.

2. Or you may also change the code of FAST-LIO, [here](https://github.com/hku-mars/FAST_LIO/blob/53ee209c125ae60b75ef33bcd837f606e1f54d2f/src/laserMapping.cpp#L979) , downsample the point cloud `pcl_wait_save` with the voxel filter in PCL lib;

3. Did you build this map for a very large scene (e.g. a 10km x 10km space) ? If not, the large size may be just because there are  too many redundant points in the map, then situation 1 or 2 will work; but if true, then you may implement your own map loader, instead of using pcl_ros, the basic idea is like google map, dividing the large map into many small tiles, and only load those tiles that are close to current localizaiton. 

For situation 3, we will also work on this,  it's best if you may provide some large-scale test maps.

**Comment by David9696** [comment]
Hi,

Thanks for your reply.

Your methods 1 and 2 are working well. Thanks for your help.

The map that we built is in a hall (90m x 40m) which is not very big in area. But we went around a few times. Hence, they are a lot of redundant points. After filtered, the map is usable for localization. 

Thanks
