### ISSUE TITLE
using offline map for odometry

### ISSUE THREAD

**Issue by ZeyingXuHuaWei** [HViktorTsoi/FAST_LIO_LOCALIZATION#5]
Hi author, I think you only use offline map for global localization, can we also use offline map to replace the online map for odometry?  Do you think this a good idea?

**Comment by HViktorTsoi** [comment]
Yes, actually we are working on this, the current version is pretty 'loosely coupled', we only use the odometry and deskewed-scan from fast-lio. In fact, it's possible to replace the local map maintained by fast-lio to the offline map, and since fast-lio-2 use a direct-matching method without feature extraction, the implementation may aslo be intuitive.

**Comment by ZeyingXuHuaWei** [comment]
Yes.  With very little modification I can now use offline map as the local map of fast-lio.

**Comment by ghost** [comment]
> Yes. With very little modification I can now use offline map as the local map of fast-lio.

Hi, I am very interested in such feature, do you mind sharing the modification?
